name: Create Release

on:
  push:
    tags:
      - 'v*'  # Run when a version tag is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build TypeScript
        run: npm run build
        
      - name: Install pkg globally
        run: npm install -g pkg
        
      - name: Package binaries
        run: |
          mkdir -p dist/bin
          pkg dist/cli/index.js --output dist/bin/griq-linux-amd64 --target node18-linux-x64
          pkg dist/cli/index.js --output dist/bin/griq-linux-386 --target node18-linux-x86
          pkg dist/cli/index.js --output dist/bin/griq-linux-arm --target node18-linux-arm
          pkg dist/cli/index.js --output dist/bin/griq-linux-arm64 --target node18-linux-arm64
          pkg dist/cli/index.js --output dist/bin/griq-darwin-amd64 --target node18-macos-x64
          pkg dist/cli/index.js --output dist/bin/griq-darwin-arm64 --target node18-macos-arm64
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/bin/griq-linux-amd64
            dist/bin/griq-linux-386
            dist/bin/griq-linux-arm
            dist/bin/griq-linux-arm64
            dist/bin/griq-darwin-amd64
            dist/bin/griq-darwin-arm64
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}